### ISSUE TITLE
Can't install in the terminal on Fedora 27

### ISSUE THREAD

**Issue by David-Else** [Jomik/vscode-search-provider#11]
Hi, I like to use the terminal to install stuff rather than websites. I am following this guide:

https://fedoramagazine.org/install-gnome-shell-extension/

I can't seem to find your extension by typing:

```
dnf search gnome-shell-extension
dnf search gnome | grep extension
dnf search VSCode*
```

How do I install via the terminal? Thanks!

**Comment by Jomik** [comment]
I suppose I would have to upload the extension to DNF, for you to be able to find it there. As the site you link says: `The list of GNOME Shell extensions you can choose from will be smaller compared to the GNOME Extensions website. `
I would not mind doing this! But, my 2 minute google search didn't find a way for me to do this.
For now, I would suggest you install it via https://extensions.gnome.org/, which also works in Chromium.

**Comment by David-Else** [comment]
Thanks for your quick reply! I thought that the DNF repo somehow accessed the Gnome Extensions one, it seems stupid that you need to upload the extension separately to another repo.

It seems I can install it through the software center, see the screenshot:

![screenshot from 2018-01-30 11-19-34](https://user-images.githubusercontent.com/12832280/35563758-a2b0eb18-05af-11e8-97db-88e4843733be.png)

(you might like to provide a screenshot to make it look cool?)

But I don't like using the software center either as it sometimes clashes with DNF. It's just a silly Fedora thing, nothing you can do anything about.

I already wrote a shell script to view and edit recent VSCode projects, so I am kind of sorted for that. I will close this thread, but if you do get it working with DNF in the future please post here :)

Thanks for taking the time to write this extension, VSCode and Gnome are AMAZING!
