### ISSUE TITLE
Doesn't seem to work with 3.28.2

### ISSUE THREAD

**Issue by MariusAlch** [Jomik/vscode-search-provider#12]
Cant get it to work with gnome  3.28.2. "Looking glass" doesnt show any omited errors

**Comment by elwerene** [comment]
@Jomik  I have the same problem, any tips how I can debug it on my machine? I am on Fedora 28 with gnome 3.28.2.

**Comment by Jomik** [comment]
@elwerene There was some additional information in #13. But I am unsure what exactly is missing. If you find anything, please update here! 👍

**Comment by elwerene** [comment]
Just to let you know, I don't have any issues at the moment with my current gnome version: 3.30.2

**Comment by Jomik** [comment]
@elwerene Thank you. I will close this for now then :)
