### ISSUE TITLE
[Feature] Support search prefix

### ISSUE THREAD

**Issue by lichensky** [Jomik/vscode-search-provider#19]
**Background:**
Sometimes there are a lot of results from other search providers when searching for project.
Search prefix could be used to distinguish search results from the vscode provider.

**Example:**
Search string with `code:` prefix -> `code:project_name`

**Comment by Jomik** [comment]
I am up for accepting a PR on this.
Perhaps add an option to allow people to customise their prefix.
Could imagine people may want to use variations.

**Comment by lichensky** [comment]
Yep, customizing of the prefix is already implemented in #20 :stuck_out_tongue:
