### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by lunaryorn** [Jomik/vscode-search-provider#26]
@Jomik If you agree I'd make a tag, and then ping you to grad the bundle from Github releases and upload it Gnome extensions.

**Comment by Jomik** [comment]
Sounds good, remember to increment the version

**Comment by lunaryorn** [comment]
I incremented the version and pushed; let's see whether the release workflow works.

If not, I'll do things manually by the weekend and ping you again :)

**Comment by lunaryorn** [comment]
@Jomik The ZIP's there :)

**Comment by Jomik** [comment]
Awesome, that's easy then. I have uploaded it now :)
