### ISSUE TITLE
Add VSCodium in supported versions

### ISSUE THREAD

**Issue by frague59** [Jomik/vscode-search-provider#29]
Just have to add :
```js
        ["codium.desktop", "VSCodium"],
```
in `candidates` array...
Could do a PR, but simpler if you do it !

Thanks !

**Comment by lunaryorn** [comment]
Please open a pull request; you can make the change right in Github's web interface 🙂

**Comment by lunaryorn** [comment]
Fixed by #30

**Comment by lunaryorn** [comment]
@Jomik I released v15 w/ this change; the release job kicked in and builds the ZIP just now, would you mind to upload it to gnome extensions?

**Comment by Jomik** [comment]
I have sent the next version (15) to review :+1: thank you
