### ISSUE TITLE
New release v16

### ISSUE THREAD

**Issue by lunaryorn** [Jomik/vscode-search-provider#32]
Hey @Jomik,

I just tagged v16, would you mind to push the artifact from <https://github.com/Jomik/vscode-search-provider/releases/tag/v16> to Gnome Extensions once its build?

This release just adds `3.36` to the list of supported Gnome Shell versions in `metadata.json`; I noticed that it wasn't there yet, and I think it's required to install this extension in Gnome 3.36.

Cheers

**Comment by Jomik** [comment]
Sent to review

**Comment by lunaryorn** [comment]
@Jomik Looks like it's published, isn't it?
