### ISSUE TITLE
Case sensitivity intended?

### ISSUE THREAD

**Issue by SantoJambit** [Jomik/vscode-search-provider#40]
Is it intended, that the search is case-sensitive?
If I search other items in the dashboard, case is usually ignored (files included).
I can create a PR to fix this if you agree.

**Comment by lunaryorn** [comment]
I don't care; all my workspaces are lowercase anyway.  If case insensitive searches work better for you please do submit a pull request.

**Comment by SantoJambit** [comment]
Created a PR. See #41
