### ISSUE TITLE
Stepping down

### ISSUE THREAD

**Issue by lunaryorn** [Jomik/vscode-search-provider#42]
@Jomik I'm sorry to say that I'll no longer help maintaining this extension.

It no longer works with Gnome 40, and I don't feel like porting it.  Migrating the settings UI to Gtk4 looks like a major hassle, and registering a search provider no longer works either—looks as if Gnome Shell shuffled things around in its code, and since search providers were never really part of the extension API to begin with there's not much help available wrt to porting.

On the other hand I discovered that writing a proper search provider isn't all that hard, and this weekend I sat down and spent an afternoon writing a proper search provider to replace another Gnome extension of mine, see https://github.com/lunaryorn/gnome-search-providers-jetbrains.  I'll do the same for VSCode, and no longer have any use for this extension.

It served me well but its time is over as far as I'm concerned; as such I'm stepping down.

Perhaps someone comes along to pick it up and replace me, but as far as I'm concerned I think you can just as well deprecate this extension and archive the repository.

I am sorry.

**Comment by Jomik** [comment]
Thanks a lot for you contributions!
That is completely understandable - it has been great 😄 
If you are creating a search provider for VSCode, that can replace this one, please let me know so that we can refer people to that one, if you want to make it public! :)

There is nothing to be sorry about, this project would have been dead long ago if you did not keep it going 😄

**Comment by lunaryorn** [comment]
@Jomik I published https://github.com/lunaryorn/gnome-search-providers-vscode to replace this extension.

Haven't added all this extension support yet, but it's a good start for Gnome 40.

**Comment by swsnr** [comment]
I'm closing this just to make it disappear from my GitHub frontpage 😊
