### ISSUE TITLE
Doesn't work with Gnome 40

### ISSUE THREAD

**Issue by StephenCoady** [Jomik/vscode-search-provider#43]
Currently this extension is showing as outdated for me on gnome 40 with fedora 34. 

Are there any plans to update it? I'm unfamiliar with GTK but if someone would like to give me pointers I'm sure I could contribute.

**Comment by StephenCoady** [comment]
Just saw the pinned issue about stopping support. Closing. Thanks anyway.

**Comment by swsnr** [comment]
Just for reference: There are no such plans currently; this extension is currently unmaintained, see #42 

I've written <https://github.com/lunaryorn/gnome-search-providers-vscode/> as an alternative which implements a proper Gnome search provider using the documented DBus interface.  It's a bit harder to install, but doesn't suffer from compatibility issues and appears in the global "Search" settings page which allows re-ordering of search results.

I've pinned this issue to make lack of Gnome 40 support more visible.

**Comment by StephenCoady** [comment]
Thanks for that. @lunaryorn is there any chance you could show me how to write the .ini file for fedora 34 and gnome 40? I use plain vscode but the file in the repo you linked doesn't seem to work for me.

**Comment by swsnr** [comment]
Please let's discuss this on the other repository.  But please understand that my time to provide support is very limited; if you'd like to have support for another VSCode variant I'm afraid you'll need to do this in your own and make a pull request.
