### ISSUE TITLE
Missing gschemas.compiled after preferences update

### ISSUE THREAD

**Issue by MariusAlch** [Jomik/vscode-search-provider#7]
Appreciate the awesome extension. But getting this error after update.

GLib.FileError: Failed to open file “/home/marius/.local/share/gnome-shell/extensions/vscode-search-provider@jomik.org/schemas/gschemas.compiled”: open() failed: No such file or directory

Stack trace:
  getSettings@/home/marius/.local/share/gnome-shell/extensions/vscode-search-provider@jomik.org/utils.js:13:18
  init@/home/marius/.local/share/gnome-shell/extensions/vscode-search-provider@jomik.org/prefs.js:10:14
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:9
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49

**Comment by Jomik** [comment]
It says the schemas file for the extension doesn't exist. This is the file that contains your preferences.
- The update allows you to choose if you want files, folders or both to be displayed.
I can see that I forgot to zip that into the zip file when uploading... I will fix that straight away, but it takes some time for the GNOME extension to be approved. You can pull the schemas folder from the repo here and put them in the directory.
https://github.com/Jomik/vscode-search-provider/tree/master/schemas
into
/home/marius/.local/share/gnome-shell/extensions/vscode-search-provider@jomik.org/schemas

**Comment by Jomik** [comment]
Extension has been approved.
