### ISSUE TITLE
Not working with "OSS" version of VSCode

### ISSUE THREAD

**Issue by m-thorsen** [Jomik/vscode-search-provider#9]
Not sure if this extension is being actively maintained and/or monitored, but thought I'd notify you about a few references in extension.js that stops this from working in Solus (and possibly other non-deb/rpm distros).

For the "OSS" version:
* the .desktop file is called "vscode-oss.desktop"
* the storage path is "~/.config/Code - OSS/storage.json"
* the command is "code-oss"

**Comment by Jomik** [comment]
I will accept a PR on this, should be easy enough to fix.
Sadly couldn't find a way to detect distro and set it based on that, but we can naively just try untill we get the desktop file, then based on that we can guess the distro.

Relevant lines in the code should be
https://github.com/Jomik/vscode-search-provider/blob/master/extension.js#L20
https://github.com/Jomik/vscode-search-provider/blob/master/extension.js#L137

**Comment by m-thorsen** [comment]
PR sent. 

First time for both Github PRs and shell extensions, so pardon any horrible-ness I may have overlooked.

**Comment by Jomik** [comment]
@m-thorsen Don't close issues manually, if you reference them in a commit/PR, then they are closed automatically when the PR/commit is accepted 👍 

I will send an update to GNOME as soon as my exam tomorrow is over, but they generally take a week or two to confirm it, till then, you can simply use my or your master, I suppose 👍
